server:
  port: 5009


spring:
  application:
    name: payment
  profiles:
    active: local

  datasource:
    url: ${JDBC_DATABASE_URL}
    username: ${JDBC_DATABASE_USERNAME}
    password: ${JDBC_DATABASE_PASSWORD}

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: "http://localhost:8080/realms/slique"

  jpa:
    hibernate:
      ddl-auto: update

# Stripe Configuration
stripe:
  secret:
    key: ${STRIPE_SECRET_KEY}
  publishable:
    key: ${STRIPE_PUBLISHABLE_KEY}
  webhook:
    secret: ${STRIPE_WEBHOOK_SECRET}

# Razorpay Configuration
razorpay:
  key:
    id: ${RAZORPAY_KEY_ID}
  secret: ${RAZORPAY_KEY_SECRET}


resilience4j:
  retry:
    instances:
      paymentGateway:
        max-attempts: 3
        wait-duration: 3s

  circuitbreaker:
    instances:
      razorpayCircuit:
        registerHealthIndicator: true
        sliding-window-size: 10
        minimum-number-of-calls: 5
        failure-rate-threshold: 50
        wait-duration-in-open-state: 30s
        permitted-number-of-calls-in-half-open-state: 3
        automatic-transition-from-open-to-half-open-enabled: true



management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,circuitbreakers,circuitbreakerevents

  endpoint:
    health:
      show-details: always

  health:
    circuitbreakers:
      enabled: true


eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
    healthcheck:
      enabled: true
